// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

#region Designer generated code

using DotBPE.Protocol.Amp;
using DotBPE.Rpc;
using Google.Protobuf;
using System.Threading.Tasks;

namespace GatewayForAspNet
{
    //start for class AbstractGreeter
    public abstract class GreeterBase : ServiceActor
    {
        protected override int ServiceId => 10006;


        public override Task<AmpMessage> ProcessAsync(AmpMessage req)
        {
            switch (req.MessageId)
            {

                //方法 Greeter.SayHello
                case 1: return this.ProcessSayHelloAsync(req);

                //方法 Greeter.SayHelloAgain
                case 2: return this.ProcessSayHelloAgainAsync(req);

                default: return base.ProcessNotFoundAsync(req);
            }
        }



        //调用委托
        private async Task<AmpMessage> ProcessSayHelloAsync(AmpMessage req)
        {
            HelloReq request = null;

            if (req.Data == null)
            {
                request = new HelloReq();
            }
            else
            {
                request = HelloReq.Parser.ParseFrom(req.Data);
            }

            req.FriendlyServiceName = "Greeter.SayHello";

            var result = await SayHelloAsync(request);
            var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);

            response.FriendlyServiceName = "Greeter.SayHello";
            response.Code = result.Code;
            if (result.Data != null)
            {
                response.Data = result.Data.ToByteArray();
            }
            return response;
        }
        //抽象方法
        public abstract Task<RpcResult<HelloRes>> SayHelloAsync( HelloReq req);

        //调用委托
        private async Task<AmpMessage> ProcessSayHelloAgainAsync(AmpMessage req)
        {
            HelloReq request = null;

            if (req.Data == null)
            {
                request = new HelloReq();
            }
            else
            {
                request = HelloReq.Parser.ParseFrom(req.Data);
            }

            req.FriendlyServiceName = "Greeter.SayHelloAgain";

            var result = await SayHelloAgainAsync(request);
            var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);

            response.FriendlyServiceName = "Greeter.SayHelloAgain";
            response.Code = result.Code;
            if (result.Data != null)
            {
                response.Data = result.Data.ToByteArray();
            }
            return response;
        }
        //抽象方法
        public abstract Task<RpcResult<HelloRes>> SayHelloAgainAsync( HelloReq req);

    }

    //end for class AbstractGreeter
}

#endregion Designer generated code