// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufObjectfactory

#region Designer generated code

using Google.Protobuf;

namespace GatewayForAspNet
{
    public class ProtobufObjectFactory
    {
        public static IMessage GetRequestTemplate(int serviceId, int messageId)
        {

    
            if (serviceId == 10006 && messageId == 1)
            {
                return new HelloReq();
            }
    
            if (serviceId == 10006 && messageId == 2)
            {
                return new HelloReq();
            }
    

            return null;
        }

        public static IMessage GetResponseTemplate(int serviceId, int messageId)
        {

    
            if (serviceId == 10006 && messageId == 1)
            {
                return new HelloRes();
            }
    
            if (serviceId == 10006 && messageId == 2)
            {
                return new HelloRes();
            }
    

            return null;
        }
    }
}

#endregion Designer generated code